# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dotnetdockerdemo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dotnetdemoregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_05d92675ba1847e1ac93b2e39fde0c9b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_151442243c464dc4b4ce2506dc069b88 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dotnetdemoregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_05d92675ba1847e1ac93b2e39fde0c9b }}/dotnetdemoimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dotnetdockerdemo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_913ef7ce9aaa4b26a29a193362a4505a }}
        images: 'dotnetdemoregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_05d92675ba1847e1ac93b2e39fde0c9b }}/dotnetdemoimage:${{ github.sha }}'